name: build
on:
  [push, pull_request]

permissions:
  contents: write

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ['9', '10', '11', '12', '13']
        os:
          - windows-latest    # win32, x86_64
          - ubuntu-latest     # linux, x86_64
          - macos-13          # macos, x86_64
          - macos-latest      # macos, arm64
    steps:
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: wheel
          condarc: |
            channels:
              - conda-forge
              - pytorch
          create-args: >-
            c-compiler
            fortran-compiler
            python=3.${{ matrix.python }}
            pkg-config
            meson-python
            xtb=6.7.1
      - uses: actions/checkout@v4
      - run: python -m pip install cibuildwheel>=3 numpy cffi
        shell: bash -el {0}
      - run: python -m cibuildwheel --archs auto --output-dir wheelhouse
        shell: bash -el {0}
        # env:
        #   SETUP_ARGS: >-
        #     -Csetup-args=-Dxtb-6.7.1:la_backend=netlib
        #     -Csetup-args=-Dmctc-lib:json=disabled
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl